version: "3"

services:
  database_rentx:
    image: postgres
    container_name: database_rentx
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    networks:
      - default
  app:
    build: .
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    networks:
      - default
    depends_on:
      - database_rentx

networks:
  default:
    driver: bridge
volumes:
  pgdata:
    driver: local
